name: Generate Prayer Times ICS

on:
  workflow_dispatch:  # Manually trigger the workflow
  schedule:
    - cron: '0 0 1 1 *'  # Runs every year on January 1st at midnight UTC

jobs:
  generate-ics:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python 3.9
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Make sure you have a requirements.txt file

      # Step 4: Run the prayer times script
      - name: Run prayer times script
        run: |
          python generate_prayer_times.py  # Ensure this matches your script name

      # Debug step: List files to check if ICS is generated
      - name: Debug output
        run: |
          ls -l  # List files in the current directory to check if the ICS file is there

      # Step 5: Commit and push the generated ICS file
      - name: Commit and push generated ICS file
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add prayer_times_2025.ics  # Update this to match the generated ICS file name
          git commit -m "Add prayer times for 2025"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
